[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DowserNN"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
tensorflow = ">=2.6.2,<3"
python = ">=3.9.15,<4"
scikit-learn = ">=1.5.2,<2"
numpy = ">=1.19.5,<2"
matplotlib = ">=3.5.3,<4"
