[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DowserML"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
tensorflow = ">=2.6.2,<3"
numpy = ">=1.19.5,<2"
matplotlib = ">=3.5.3,<4"
keras = ">=3.6.0,<4"
