[project]
channels = ["conda-forge"]
description = "Add a short description here"
name = "DowserML"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda="12.0"

[tasks]

[dependencies]
python = "3.11.*"
matplotlib = ">=3.9.2,<4"
numpy = ">=2.1.3,<3"
tensorflow=">=2.17.0, <3"
